---
title: "StatsBomb Women's World Cup Data"
author: "saintsnumbers"
output: github_document
date: 2019-08-09
editor_options: 
  chunk_output_type: inline
---

[**Guide**](http://statsbomb.com/wp-content/uploads/2019/07/Using-StatsBomb-Data-In-R-English.pdf)

```{r setup, include=FALSE}
# knitr::opts_chunk$set(echo = FALSE)

#libraries
library(tidyverse)
library(devtools)
library(knitr)
library(kableExtra)
library(StatsBombR)
library(SBpitch)
theme_set(theme_bw())
# search()
# detach(package())
rm(list=ls())
```

```{r import, include=FALSE}
statsbombdata <- FreeCompetitions() %>%
  filter(competition_name=="Women's World Cup" & season_name=="2019") %>%
  FreeMatches() %>%
  StatsBombFreeEvents(MatchesDF=.,Parallel=TRUE) %>%
  allclean()
```

1. Shots and goals
1. Graphing shots on a chart
1. Player shots per 90
1. Mapping passes

## Shots and Goals

```{r shots and goals}
statsbombdata %>%
  group_by(team.name) %>%
  summarise(shots=sum(type.name=="Shot",na.rm=TRUE),
            goals=sum(shot.outcome.name=="Goal",na.rm=TRUE))
```

## Graphing shots on a chart

```{r data to chart}
statsbombdata %>%
  group_by(team.name) %>%
  summarise(shots=sum(type.name=="Shot",na.rm=TRUE),
            goals=sum(shot.outcome.name=="Goal",na.rm=TRUE)) %>%
  ggplot(aes(x=reorder(team.name,shots),y=shots)) +
  geom_bar(stat="identity",width=.5) +
  labs(x="Team",y="Shots") +
  theme(axis.title.y=element_blank()) +
  scale_y_continuous(expand=c(0,0)) +
  coord_flip()

statsbombdata %>%
  group_by(team.name) %>%
  summarise(shots=sum(type.name=="Shot",na.rm=TRUE),
            goals=sum(shot.outcome.name=="Goal",na.rm=TRUE)) %>%
  gather(type,value,-team.name) %>%
  ggplot(aes(x=reorder(team.name,value),y=value,fill=type)) +
  geom_bar(stat="identity",position="dodge") +
  labs(x="Team",y="Shots/Goals") +
  theme(axis.title.x=element_blank(),axis.title.y=element_blank()) +
  scale_y_continuous(expand=c(0,0)) +
  coord_flip()
```

## Player shots per 90

```{r shots per 90}
statsbombdata %>%
  group_by(player.name,player.id) %>%
  summarise(shots=sum(type.name=="Shot",na.rm=TRUE)) %>%
  left_join(statsbombdata %>%
              get.minutesplayed() %>%
              group_by(player.id) %>%
              summarise(minutes=sum(MinutesPlayed))) %>%
  mutate(shotsper90=(shots/minutes)*90) %>%
  arrange(-shots)
```

## Plotting passes

```{r plotting passes}
types <- statsbombdata %>%
  select(type.name) %>%
  unique

teams <- statsbombdata %>%
  select(team.name) %>%
  unique

statsbombdata %>%
  filter

eng_passes <- statsbombdata %>%
  filter(team.name=="England Women's") %>%
  filter(type.name=="Pass")

create_Pitch() +
  geom_segment(data=eng_passes,aes(x=location.x,y=location.y,xend=pass.end_location.x,yend=pass.end_location.y),
               lineend="round",size=0.5,arrow=arrow(length=unit(0.15,"cm"))) +
  labs(title="England passes",subtitle="Women's World Cup 2019") +
  coord_fixed(ratio=105/100)
```

```{r plotting shots}
jam_shots <- statsbombdata %>%
  filter(team.name=="Jamaica Women's") %>%
  filter(type.name=="Shot")
  # discard(~all(is.na(.x)))
  # View("jamaica shots")

create_Pitch() +
  geom_segment(data=jam_shots,aes(x=location.x,y=location.y,xend=shot.end_location.x,yend=shot.end_location.y),
               lineend="round",size=0.5,arrow=arrow(length=unit(0.15,"cm"))) +
  labs(title="Jamaica shots",subtitle="Women's World Cup 2019") +
  coord_fixed(ratio=105/100)
```

```{r plotting pressures}
# prc_pressures <- statsbombdata %>%
#   filter(team.name=="China PR Women's") %>%
#   filter(type.name=="Pressure") %>%
#   discard(~all(is.na(.x))) %>%
#   View("china pressures")
```