---
title: "Southampton FC Transfermarkt Scraper"
author: "saintsnumbers"
output: github_document
date: 2019-07-28
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
# knitr::opts_chunk$set(echo = FALSE)

#libraries
library(tidyverse)
library(rvest)
# theme_set(theme_bw())


#delete environment variables
rm(list=ls())
```

# Scraping Southampton FC Transfermarkt data.

## Plan

* Load the webpage containing the data.
* Locate the data within the page and extract it.
* Organise the data into a dataframe

## Load the webpage

* [**Southampton FC Transfermarkt** (detailed)](https://www.transfermarkt.co.uk/southampton-fc/kader/verein/180/saison_id/2019/plus/1)
* [Page used in the example](https://www.transfermarkt.co.uk/manchester-city/startseite/verein/281/saison_id/2019)

```{r load}
page_url <- "https://www.transfermarkt.co.uk/southampton-fc/kader/verein/180/saison_id/2019/plus/1"
page_scraped <- read_html(page_url)
```

## Extract the data

* **Name**
* *Squad Number*
* *DOB/Age*
* *Height*
* *Foot*
* *Joined*
* *Contract*

```{r}
player_names <- page_scraped %>%
  html_nodes(".spielprofil_tooltip") %>%
  html_text()

player_names <- player_names[seq(1,length(player_names),2)] #duplicated - odd numbered data only
head(player_names,12)
```

