---
# title: "Southampton FC Understat Scraper"
# author: "saintsnumbers"
output:
  github_document:
    fig_height: 3
# date: 2019-08-14
editor_options:
  chunk_output_type: inline
---

# Understat Data

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE)

#libraries
library(tidyverse)
library(rvest)
library(magrittr)
library(understatr)
library(ggsoccer)
library(ggtext)
library(ggrepel)
set.seed(9999)
theme_set(theme_bw())

#delete environment variables
rm(list=ls())

team <- "Southampton"
year <- 2019
source <- c(team,year)
```

## Season `r source[[2]]` plots

```{r plots}
get_team_players_stats(source[[1]],source[[2]]) %>%
  filter(time>0) %>%
  mutate(player_name=factor(player_name,levels=player_name[order(time)])) %>%
  ggplot(aes(x=player_name,y=time)) +
  geom_bar(stat="identity",fill="#e61919",width=0.8,alpha=0.6) +
  labs(title=paste0("League minutes ",as.integer(source[[2]]),"-",as.integer(source[[2]])+1)) +
  theme(axis.title.x=element_blank(),axis.title.y=element_blank()) +
  coord_flip()
ggsave(paste0("./plots/",source[[2]],"/",source[[1]],"_minutes.jpg"))

get_team_players_stats(source[[1]],source[[2]]) %>%
  filter(xG > 0) %>%
  mutate(player_name=factor(player_name,levels=player_name[order(xG)])) %>%
  ggplot(aes(x=player_name,y=xG)) +
  geom_bar(stat="identity",fill="#e61919",width=0.8,alpha=0.6) +
  labs(title=paste0("League xG ",as.integer(source[[2]]),"-",as.integer(source[[2]])+1)) +
  theme(axis.title.x=element_blank(),axis.title.y=element_blank()) +
  coord_flip()
ggsave(paste0("./plots/",source[[2]],"/",source[[1]],"_xG",".jpg"))

get_team_players_stats(source[[1]],source[[2]]) %>%
  filter((xG > 0)|(xA > 0)) %>%
  ggplot(aes(x=xG,y=xA)) +
  geom_point(colour="#e61919",alpha=0.6) +
  # geom_text(aes(label=ifelse(xG+xA>=1,player_name,""),hjust="inward",vjust="outward"),size=1.5) +
  geom_text_repel(aes(label=ifelse(xG+xA>=0.1,player_name,"")),size=2) +
  labs(title=paste0("League xG/xA ",as.integer(source[[2]]),"-",as.integer(source[[2]])+1),x="xG",y="xA") +
  coord_fixed()
ggsave(paste0("./plots/",source[[2]],"/",source[[1]],"_xG_xA_point.jpg"))

get_team_players_stats(source[[1]],source[[2]]) %>%
  filter((xG > 0)|(xA > 0)) %>%
  mutate(player_name=factor(player_name,levels=player_name[order(xG)])) %>%
  gather("xG","xA",key="x",value="xN") %>%
  select("player_name","x","xN") %>%
  mutate(x=factor(x,levels=c("xG","xA"))) %>%
  ggplot(aes(x=player_name,y=xN,fill=x)) +
  geom_bar(stat="identity",position="dodge") +
  labs(title=paste0("League xG/xA ",as.integer(source[[2]]),"-",as.integer(source[[2]])+1)) +
  theme(axis.title.x=element_blank(),axis.title.y=element_blank(),legend.title=element_blank()) +
  coord_flip()
ggsave(paste0("./plots/",source[[2]],"/",source[[1]],"_xG_xA_bar.jpg"))

get_team_players_stats(source[[1]],source[[2]]) %>%
  filter(shots > 0) %>%
  mutate(player_name=factor(player_name,levels=player_name[order(shots)])) %>%
  ggplot(aes(x=player_name,y=shots)) +
  geom_bar(stat="identity",fill="#e61919",width=0.8,alpha=0.6) +
  labs(title=paste0("Shots ",as.integer(source[[2]]),"-",as.integer(source[[2]])+1)) +
  theme(axis.title.x=element_blank(),axis.title.y=element_blank()) +
  coord_flip()
ggsave(paste0("./plots/",source[[2]],"/",source[[1]],"_shots.jpg"))

get_team_players_stats(source[[1]],source[[2]]) %>%
  filter(shots > 0) %>%
  mutate(shots_per_90=(shots/time)*90) %>%
  mutate(player_name=factor(player_name,levels=player_name[order(shots_per_90)])) %>%
  ggplot(aes(x=player_name,y=shots_per_90)) +
  geom_bar(stat="identity",fill="#e61919",width=0.8,alpha=0.6) +
  labs(title=paste0("Shots per 90 ",as.integer(source[[2]]),"-",as.integer(source[[2]])+1)) +
  theme(axis.title.x=element_blank(),axis.title.y=element_blank()) +
  coord_flip()
ggsave(paste0("./plots/",source[[2]],"/",source[[1]],"_shots_per_90_bar.jpg"))

get_team_players_stats(source[[1]],source[[2]]) %>%
  filter(shots > 0) %>%
  mutate(shots_per_90=(shots/time)*90) %>%
  filter(shots_per_90 > 1) %>%
  ggplot(aes(x=time,y=shots_per_90)) +
  geom_point(colour="#e61919",alpha=0.6) +
  geom_text_repel(aes(label=player_name),size=2) +
  labs(title=paste0("Shots per 90 ",as.integer(source[[2]]),"-",as.integer(source[[2]])+1),x="Minutes",y="Shots per 90")
ggsave(paste0("./plots/",source[[2]],"/",source[[1]],"_shots_per_90_point.jpg"))

get_team_players_stats(source[[1]],source[[2]]) %>%
  filter(key_passes > 0) %>%
  mutate(player_name=factor(player_name,levels=player_name[order(key_passes)])) %>%
  ggplot(aes(x=player_name,y=key_passes)) +
  geom_bar(stat="identity",fill="#e61919",width=0.8,alpha=0.6) +
  labs(title=paste0("Key passes ",as.integer(source[[2]]),"-",as.integer(source[[2]])+1)) +
  theme(axis.title.x=element_blank(),axis.title.y=element_blank()) +
  coord_flip()
ggsave(paste0("./plots/",source[[2]],"/",source[[1]],"_keypasses.jpg"))

get_team_players_stats(source[[1]],source[[2]]) %>%
  filter(shots > 0) %>%
  mutate(xG_per_shot = npxG/shots) %>%
  filter(shots >= 4) %>%
  ggplot(aes(x=shots,y=xG_per_shot)) +
  geom_point(colour="#e61919",alpha=0.6) +
  geom_text_repel(aes(label=player_name),size=2) +
  scale_x_continuous(breaks=seq(0,14,2)) +
  # scale_y_continuous() +
  expand_limits(x=c(4,13),y=0) +
  labs(title=paste0("xG per shot ",as.integer(source[[2]]),"-",as.integer(source[[2]])+1),x="Shots",y="xG per shot")
ggsave(paste0("./plots/",source[[2]],"/",source[[1]],"_shots_xG_per_shot.jpg"))

get_team_players_stats(source[[1]],source[[2]]) %>%
  filter(shots > 0) %>%
  mutate(xG_per_shot = xG/shots) %>%
  mutate(player_name=factor(player_name,levels=player_name[order(xG_per_shot)])) %>%
  ggplot(aes(x=player_name,y=xG_per_shot)) +
  geom_bar(stat="identity",fill="#e61919",width=0.8,alpha=0.6) +
  labs(title=paste0("League xG per shot ",as.integer(source[[2]]),"-",as.integer(source[[2]])+1)) +
  theme(axis.title.x=element_blank(),axis.title.y=element_blank()) +
  coord_flip()
ggsave(paste0("./plots/",source[[2]],"/",source[[1]],"_xG_per_shot.jpg"))
```

## Test plots

```{r test plots}
id_che <- get_team_players_stats("Southampton",2019) %>%
  filter(player_name == "Che Adams") %>%
  select(player_id,player_name)

epl_teams <- get_league_teams_stats("EPL",2019) %>%
  select(team_id,team_name) %>%
  unique()
```

## Shot maps

```{r shots}
get_match_shots(11666) %>%
  mutate(team = ifelse(h_a == "h", h_team, a_team)) %>%
  filter(team == "Southampton") %>%
  ggplot() +
  annotate_pitch(colour="white",fill="chartreuse3",limits=FALSE) +
  geom_point(aes(x=100*X,y= 100*Y),colour="#e61919",size=3) +
  theme_pitch() +
  theme(plot.background = element_rect(fill="chartreuse3"),title=element_text(colour="black")) +
  coord_flip(xlim = c(49, 101),ylim = c(-1, 101)) +
  ggtitle("Brighton v Southampton","Southampton shots")
```

## Data

```{r data, echo=F, eval=F}
get_match_shots(11666) %>%
  mutate(team = ifelse(h_a == "h", h_team, a_team)) %>%
  group_by(team,situation,result) %>%
  summarise(n = n())
```