---
title: "Understat Scraper"
author: "saintsnumbers"
output: github_document
date: 2019-08-16
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
# knitr::opts_chunk$set(echo = FALSE)

#libraries
library(tidyverse)
library(rvest)
library(magrittr)

library(stringi)
library(qdapRegex)
library(jsonlite)

# remotes::install_github('ewenme/understatr')
library(understatr)
theme_set(theme_bw())

#delete environment variables
rm(list=ls())
```

```{r,include=FALSE}
# source("understat-global-objects.R")
# source("understat-scraper-teams.R")
# source("understat-scraper-seasons.R")
# source("understat-scraper-players.R")
# source("understat-scraper-matches.R")
```

## [Understatr](https://github.com/ewenme/understatr)

### List of methods

```{r understatr methods, echo=FALSE}
ls("package:understatr")
```

### League

```{r understatr league}
get_leagues_meta()

get_league_seasons("EPL") %>%
  glimpse

get_league_teams_stats("EPL",2018) %>%
  glimpse
```

### Team

```{r understatr team}
get_team_meta("Southampton")

get_team_players_stats("Southampton",2019) %>%
  glimpse %>%
  head
```

### Player

```{r understatr player}
get_player_matches_stats(1734) %>%
  glimpse %>%
  head

get_player_seasons_stats(1734) %>%
  glimpse %>%
  head

get_player_shots(790) %>%
  glimpse %>%
  head
```

### Match

```{r understatr match}
get_match_shots(11658) %>%
  glimpse %>%
  head

get_match_stats(11658) %>%
  glimpse %>%
  head
```