---
# title: "fbref scraper"
# author: "saintsnumbers"
output:
  github_document:
    # fig_height: 3
# date: 2019-10-09
editor_options:
  chunk_output_type: console
---

```{r setup,include=F}
knitr::opts_chunk$set(echo=F,message=F,warning=F)

library(tidyverse)
library(magrittr)
library(rvest)
# library(understatr)
# library(ggsoccer)
library(ggrepel)
library(ggthemes)
library(here)

set.seed(9999)

source(here("R","fbref","fbref-themes.R"))
```

```{r scraper,eval=F}
# scrape data from fbref and save locally
# run only this block to scrape data and save
# (ctrl+shift+F10 :: ctrl+shift+enter)
# raw <- list()
# source(here("R","fbref","scraper","fbref-scraper-functions.R"))
# source(here("R","fbref","scraper","fbref-scraper.R"))
# source(here("R","fbref","scraper","fbref-scraper-save.R"))
```

```{r read}
# read from saved fbref data
raw <- list()
source(here("R","fbref","scraper","fbref-scraper-read.R"))
```

```{r tidy}
# tidy raw fbref data
tidy <- list()
source(here("R","fbref","tidy","fbref-tidy-players.R"))
source(here("R","fbref","tidy","fbref-tidy-teams.R"))
source(here("R","fbref","tidy","fbref-tidy-matches.R"))
rm(raw,tidy)
```

### Southampton plots

```{r plots-sfc}
players %>%
  filter(Squad=="Southampton") %>%
  filter(!is.na(Min)) %>%
  mutate(
    Min=replace(Min,is.na(Min),0),
    Subs=replace(Subs,is.na(Subs),0),
    `Mn/Sub`=replace(`Mn/Sub`,is.na(`Mn/Sub`),0),
    MinSub=Subs*`Mn/Sub`,
    MinStart=Min-MinSub,
    ) %>%
  mutate(
    Pos1=ifelse(Player %in% c("Kevin Danso","Jannik Vestergaard","Jan Bednarek","Jack Stephens","Maya Yoshida"),"CB",Pos1),
    Pos1=ifelse(Player %in% c("Ryan Bertrand","Cédric Soares","Yan Valery"),"FB",Pos1),
    Pos1=ifelse(Player %in% c("James Ward-Prowse","Pierre Højbjerg","Oriol Romeu","William Smallbone"),"DM",Pos1),
    Pos1=ifelse(Player %in% c("Nathan Redmond","Stuart Armstrong","Sofiane Boufal","Moussa Djenepo"),"AM",Pos1),
  ) %>%
  mutate(Possfc=factor(Pos1,levels=c("GK","CB","FB","DM","AM","FW"))) %>%
  mutate(Player=fct_reorder(Player,Min)) %>%
  ggplot(aes(x=Min,y=Player)) +
  geom_segment(aes(y=Player,yend=Player,x=0,xend=MinStart),colour=sfc,size=3.5,alpha=0.8) +
  geom_segment(aes(y=Player,yend=Player,x=MinStart,xend=Min),colour=sfc,size=3.5,alpha=0.3) +
  # geom_label(aes(label=Min),colour=sfc_light,size=2) +
  theme_sfc() +
  labs(title="League minutes",
       subtitle="(from start / from bench)",
       x=element_blank(),
       y=element_blank(),
       caption=caption[[1]]) +
  expand_limits(Min=0) +
  scale_x_continuous(breaks=seq(0,90*38,180),expand=expand_scale(add=c(20,20))) +
  theme(
    axis.line=element_blank(),
    axis.text.x=element_text(size=rel(0.8),hjust=0.5),
    axis.text.y=element_text(size=rel(0.8)),
    strip.background=element_blank(),
    strip.text.y=element_text(colour="black",face="bold",angle=0),
  ) +
  facet_grid(Possfc ~ .,scales="free",space="free")
ggsave(here("plots","SFC","Minutes.jpg"))

players %>%
  filter(Squad=="Southampton") %>%
  filter(!is.na(npxG)|!is.na(xA)) %>%
  mutate(focus=ifelse(npxG>=1|xA>=1,TRUE,FALSE)) %>%
  ggplot(aes(x=npxG,y=xA)) +
  geom_blank(data=data.frame(npxG=0,xA=0)) +
  geom_point(aes(fill=focus),shape=21,size=3,alpha=0.8,colour="black") +
  geom_text_repel(aes(label=ifelse(focus,Player,"")),size=rel(4)) +
  theme_sfc() +
  labs(title="Southampton xG/xA",
       x="Expected goals",
       y="Expected assists",
       caption="statsbomb/fbref") +
  scale_x_continuous(breaks=seq(0,30,1),expand=expand_scale(add=c(0,0.1))) +
  scale_y_continuous(breaks=seq(0,30,1),expand=expand_scale(add=c(0,0.1))) +
  scale_fill_manual(values=c("lightgrey",sfc)) +
  coord_fixed()
ggsave(here("plots","SFC","npxGxA.jpg"))

players %>%
  filter(Squad=="Southampton") %>%
  filter(!is.na(xG90)|!is.na(xA90)) %>%
  mutate(focus=ifelse(xG90>=0.07|xA90>=0.07,TRUE,FALSE)) %>%
  ggplot(aes(x=npxG90,y=xA90)) +
  geom_blank(data=data.frame(npxG90=0,xA90=0)) +
  geom_point(aes(fill=focus),shape=21,size=2,alpha=0.8,colour="black") +
  geom_text_repel(aes(label=ifelse(focus,Player,"")),size=rel(3)) +
  theme_sfc() +
  labs(title="Southampton xG/xA",
       subtitle="(per 90 mins)",
       x="Expected goals per 90 minutes",
       y="Expected assists per 90 minutes",
       caption=caption[[1]]) +
  scale_x_continuous(breaks=seq(0,2,0.1),expand=expand_scale(add=c(0,0.02))) +
  scale_y_continuous(breaks=seq(0,2,0.1),expand=expand_scale(add=c(0,0.02))) +
  scale_fill_manual(values=c("lightgrey",sfc)) +
  coord_fixed()
ggsave(here("plots","SFC","SFCnpxGxA90.jpg"))

players %>%
  filter(Squad=="Southampton") %>%
  filter(!is.na(`Gls+/-`)) %>%
  mutate(Player=fct_reorder(Player,`Gls+/-`)) %>%
  mutate(Pos=ifelse(`Gls+/-`>=0,TRUE,FALSE)) %>%
  ggplot(aes(x=`Gls+/-`,y=Player,colour=Pos)) +
  geom_segment(aes(x=0,xend=`Gls+/-`,y=Player,yend=Player),size=4,alpha=0.8) +
  theme_sfc() +
  labs(title="On-pitch goal difference",
       x=element_blank(),
       y="Goals scored - Goals conceded",
       caption=caption[[1]]) +
  scale_colour_manual(values=c(col_medium[8],col_medium[3])) +
  scale_x_reverse(breaks=seq(-100,100,2),expand=expand_scale(add=0.1))
ggsave(here("plots","SFC","GoalDifference.jpg"))

# players %>%
#   filter(Squad=="Southampton") %>%
#   filter(!is.na(`xG+/-`)) %>%
#   mutate(Player=fct_reorder(Player,onxGA,.desc=TRUE)) %>%
#   mutate(Pos=ifelse(onxGA>=0,TRUE,FALSE)) %>%
#   ggplot(aes(x=onxGA,y=Player,colour=Pos)) +
#   geom_segment(aes(x=0,xend=onxGA,y=Player,yend=Player),size=4,alpha=0.8) +
#   theme_sfc() +
#   labs(title="On-pitch expected goals against",
#        x="xG difference",
#        y=element_blank(),
#        caption="statsbomb/fbref") +
#   scale_colour_manual(values=c(col_medium[8],col_medium[3]))
# ggsave(here("plots","SFC","GoalsAgainstxG.jpg"))

players %>%
  filter(Squad=="Southampton") %>%
  filter(!is.na(`xG+/-`)) %>%
  mutate(Player=fct_reorder(Player,`xG+/-`)) %>%
  mutate(Pos=ifelse(`xG+/-`>=0,TRUE,FALSE)) %>%
  ggplot(aes(x=`xG+/-`,y=Player,colour=Pos)) +
  geom_segment(aes(x=0,xend=`xG+/-`,y=Player,yend=Player),size=4,alpha=0.8) +
  theme_sfc() +
  labs(title="On-pitch expected goals difference",
       x="xG difference",
       y=element_blank(),
       caption=caption[[1]]) +
  scale_colour_manual(values=c(col_medium[8],col_medium[3])) +
  scale_x_reverse(breaks=seq(-100,100,2),expand=expand_scale(add=0.1))
ggsave(here("plots","SFC","GoalDifferencexG.jpg"))

players %>%
  filter(Squad=="Southampton") %>%
  filter(!is.na(`xG+/-90`)) %>%
  mutate(Player=fct_reorder(Player,`xG+/-90`)) %>%
  mutate(Pos=ifelse(`xG+/-90`>=0,TRUE,FALSE)) %>%
  ggplot(aes(x=`xG+/-90`,y=Player,colour=Pos)) +
  geom_segment(aes(x=0,xend=`xG+/-90`,y=Player,yend=Player),size=4,alpha=0.8) +
  theme_sfc() +
  labs(title="On-pitch expected goals difference",
       subtitle="(per 90 mins)",
       x=element_blank(),
       y="xG difference per 90 minutes",
       caption=caption[[1]]) +
  scale_colour_manual(values=c(col_medium[8],col_medium[3])) +
  scale_x_reverse(breaks=seq(-2,2,0.1),expand=expand_scale(add=0.01))
ggsave(here("plots","SFC","GoalDifferencexG90.jpg"))
```

### Premier League player plots

```{r plots-epl-players}
players %>%
  filter(Gls==0) %>%
  filter(Pos1=="FW" | Pos2=="FW") %>%
  filter(Sh>=3&npxG>=0.3) %>%
  # filter(Player!="David McGoldrick") %>%
  ggplot(aes(x=npxG,y=Sh)) +
  geom_blank(data=data.frame(npxG=0,Sh=0)) +
  geom_text_repel(aes(label=Player),size=2) +
  geom_point(aes(colour=Squad),size=3,shape=4) +
  theme_epl() +
  labs(title="Who hasn't scored yet?",
       subtitle="Forwards with 3+ shots, 0 goals",
       x="Expected goals",
       y="Shots",
       caption=caption[[1]]) +
  scale_colour_manual(values=palette_epl()) +
  expand_limits(x=0,y=10) +
  scale_x_continuous(breaks=seq(0,30,0.5),expand=expand_scale(add=c(0,0.2))) +
  scale_y_continuous(breaks=seq(0,50,5),expand=expand_scale(add=c(0,0.5)))
ggsave(here("plots","EPL","NoGoalsxGShots.jpg"))
```

### Premier League team plots

```{r plots-epl-teams}
squad %>%
  mutate(Squad=fct_reorder(Squad,npxG)) %>%
  ggplot(aes(x=Squad,y=npxG,colour=Squad)) +
  geom_segment(aes(x=0,xend=npxG,y=Squad,yend=Squad),size=4,alpha=0.8) +
  theme_epl() +
  theme(panel.grid.major.y=element_blank()) +
  labs(title="Premier League expected goals",
       x=element_blank(),
       y=element_blank(),
       caption=caption[[1]]) +
  scale_colour_manual(values=palette_epl()) +
  scale_x_continuous(breaks=seq(0,200,5),expand=expand_scale(add=c(0,0.5)))
ggsave(here("plots","EPL","npxG.jpg"))

squad %>%
  mutate(Squad=fct_reorder(Squad,xGA,.desc=TRUE)) %>%
  ggplot(aes(x=Squad,y=xGA,colour=Squad)) +
  geom_segment(aes(x=0,xend=xGA,y=Squad,yend=Squad),size=4,alpha=0.8) +
  theme_epl() +
  theme(panel.grid.major.y=element_blank()) +
  labs(title="Premier League expected goals allowed",
       x=element_blank(),
       y=element_blank(),
       caption=caption[[1]]) +
  scale_colour_manual(values=palette_epl()) +
  scale_x_continuous(breaks=seq(0,200,5),expand=expand_scale(add=c(0,0.5)))
ggsave(here("plots","EPL","npxGA.jpg"))

squad %>%
  mutate(Squad=fct_reorder(Squad,`np:G-xG`)) %>%
  ggplot(aes(x=Squad,y=`np:G-xG`,colour=Squad)) +
  geom_segment(aes(x=0,xend=`np:G-xG`,y=Squad,yend=Squad),size=4,alpha=0.8) +
  theme_epl() +
  labs(title="Expected goals over/underperformance",
       x=element_blank(),
       y=element_blank(),
       caption=caption[[1]]) +
  scale_colour_manual(values=palette_epl()) +
  scale_x_continuous(breaks=seq(-50,50,2),expand=expand_scale(add=0.1))
ggsave(here("plots","EPL","npG-xG.jpg"))

squad %>%
  mutate(`xGA-GA`=xGA-GA) %>%
  mutate(Squad=fct_reorder(Squad,`xGA-GA`)) %>%
  ggplot(aes(x=Squad,y=`xGA-GA`,colour=Squad)) +
  geom_segment(aes(x=0,xend=`xGA-GA`,y=Squad,yend=Squad),size=4,alpha=0.8) +
  theme_epl() +
  labs(title="Expected goals allowed over/underperformance",
       x=element_blank(),
       y=element_blank(),
       caption=caption[[1]]) +
  scale_colour_manual(values=palette_epl()) +
  scale_x_continuous(breaks=seq(-50,50,2),expand=expand_scale(add=0.1))
ggsave(here("plots","EPL","npxGA-GA.jpg"))

squad %>%
  mutate(Squad=fct_reorder(Squad,xGDiff)) %>%
  ggplot(aes(x=Squad,y=xGDiff,colour=Squad)) +
  geom_segment(aes(x=0,xend=xGDiff,y=Squad,yend=Squad),size=4,alpha=0.8) +
  # geom_bar(stat="identity",alpha=0.8) +
  theme_epl() +
  labs(title="Expected goal difference",
       x=element_blank(),
       y=element_blank(),
       caption=caption[[1]]) +
  scale_colour_manual(values=palette_epl()) +
  scale_x_continuous(breaks=seq(-50,50,5),expand=expand_scale(add=0.1))
ggsave(here("plots","EPL","xGD.jpg"))

squad %>%
  ggplot(aes(x=npxG,y=xGA)) +
  geom_text_repel(aes(label=Squad),size=2) +
  geom_point(aes(colour=Squad),size=3,shape=4) +
  theme_epl() +
  labs(title="Expected goals",
       x="xG for",
       y="xG against",
       caption=caption[[1]]) +
  scale_x_continuous(breaks=seq(0,100,5),expand=expand_scale(add=c(4,2))) +
  scale_y_continuous(breaks=seq(0,100,5),expand=expand_scale(add=c(4,2))) +
  scale_colour_manual(values=palette_epl()) +
  coord_fixed()
ggsave(here("plots","EPL","xGFxGA.jpg"))
```

```{r test,eval=F}
# pass footedness bar
players %>%
  filter(Squad=="Southampton") %>% 
  filter(!is.na(Left)&!is.na(Right)) %>%
  mutate(PassRatio=(max(Left,Right)/(Left+Right)) %>% abs %>% round(digits=2)) %>%
  gather("Left","Right",key="PassFoot",value="Passes") %>%
  ggplot(aes(x=reorder(Player,Passes),y=Passes)) +
  geom_bar(aes(fill=PassFoot),stat="identity") +
  # theme_sfc() +
  labs(title=element_blank(),
       x=element_blank(),
       y="Total passes",
       caption=caption[[1]],
       legend.position="right") +
  scale_fill_manual(values=c(col_medium[[1]],col_medium[[8]])) +
  coord_flip()

# pass footnedness two-sided bar
players %>%
  filter(Squad=="Southampton") %>%
  filter(!is.na(Left)&!is.na(Right)) %>%
  mutate(Passes=Left+Right) %>%
  ggplot(aes(x=reorder(Player,Passes))) +
  geom_bar(aes(y=Right),stat="identity",fill=col_light[[1]]) +
  geom_bar(aes(y=-Left),stat="identity",fill=col_medium[[8]]) +
  # theme_sfc() +
  coord_flip()

# passes by type
players %>%
  filter(Squad=="Southampton") %>%
  pivot_longer(cols=c(ShortCmp,MediumCmp,LongCmp),names_to="PassType",values_to="Cmp") %>%
  ggplot(aes(x=Player,y=Cmp,fill=PassType)) +
  geom_bar(stat="identity") +
  coord_flip()

# https://ryo-n7.github.io/2019-11-28-visualize-EPL-part-2/
players %>%
  filter(Squad=="Southampton") %>%
  pivot_longer(cols=c(ShortCmp,MediumCmp,LongCmp),names_to="PassType",values_to="Cmp") %>%
  mutate(PassType=factor(PassType,labels=c("Short","Medium","Long"))) %>%
  ggplot(aes(x=0,y=Cmp,label=Player)) +
  geom_point(size=2,colour=sfc) +
  geom_text_repel(
    size=3,
    nudge_x=0.3,
    direction="y",
    hjust=0,
    segment.size=0
  ) +
  theme_sfc() +
  theme(
    axis.line.x=element_blank(),
    axis.ticks.x=element_blank(),
    axis.text.x=element_blank(),
    axis.title.x=element_blank(),
    panel.grid.major.x=element_blank(),
  ) +
  facet_wrap("PassType",scales="free") +
  labs(title="Completed passes",
       x=element_blank(),
       y=element_blank(),
       caption=caption[[1]]) +
  scale_x_continuous(limit=c(0,1)) +
  scale_y_continuous()


players %>%
  filter(Squad=="Southampton") %>%
  pivot_longer(cols=c(`ShortCmp%`,`MediumCmp%`,`LongCmp%`),names_to="PassType",values_to="Cmp%") %>%
  mutate(PassType=factor(PassType,levels=c("ShortCmp%","MediumCmp%","LongCmp%"))) %>%
  ggplot(aes(x=0,y=`Cmp%`,label=Player,colour=PassType)) +
  geom_point(size=2) +
  facet_wrap("PassType") +
  scale_y_continuous(labels=function(x){paste0(x,"%")})

players %>%
  filter(Pos1 %in% c("MF","FW")) %>%
  top_n(20, Min) %>%
  ggplot(aes(x=reorder(Player,Min),y=Min,fill=Pos1)) +
  geom_bar(stat="identity",width=0.8,alpha=0.8) +
  geom_label(aes(label=Min),fontface="bold",size=2) +
  theme_epl() +
  theme(panel.grid.major.y=element_blank(),
        axis.text.x=element_text(hjust=0.5,size=rel(0.8))) +
  labs(title="League minutes (MF/FW)",
       x=element_blank(),
       y=element_blank(),
       caption=caption[[1]]) +
  scale_fill_manual(values=c(col_gdocs[[2]],col_gdocs[[4]],col_gdocs[[6]])) +
  scale_y_continuous(breaks=seq(0,90*38,180),expand=expand_scale(add=c(-1000,80))) +
  coord_flip()

players %>%
  filter(Gls==0) %>%
  filter(Pos1=="FW" | Pos2=="FW") %>%
  filter(Sh>=6) %>%
  # filter(Player!="David McGoldrick") %>%
  ggplot(aes(x=npxG,y=Sh)) +
  geom_text_repel(aes(label=Player),size=2) +
  geom_point(aes(colour=Squad),size=3,shape=4) +
  theme_epl() +
  labs(title="Who hasn't scored yet?",
       subtitle="Forwards with 6+ shots, 0 goals",
       x="Expected goals",
       y="Shots",
       caption=caption[[1]]) +
  scale_colour_manual(values=palette_epl()) +
  expand_limits(x=0,y=10) +
  scale_x_continuous(breaks=seq(0,30,0.5),expand=expand_scale(add=c(0,0.2))) +
  scale_y_continuous(breaks=seq(0,50,5),expand=expand_scale(add=c(0.5,0.5))) #include 0?

matches %>%
  # mutate(sub="Southampton") %>%
  filter(Home=="Southampton" | Away=="Southampton") %>%
  filter(is.na(xGHome)==FALSE) %>%
  mutate(
    xGF=ifelse(Home=="Southampton",xGHome,xGAway),
    xGA=ifelse(Home=="Southampton",xGAway,xGHome)
    ) %>%
  ggplot(aes(x=Wk,y=xGHome)) +
  geom_line()

matches %>%
  mutate(sub="Southampton") %>%
  filter(Home==sub | Away==sub) %>%
  filter(is.na(xGHome)==FALSE) %>%
  mutate(
    xGF=ifelse(Home==sub,xGHome,xGAway),
    xGA=ifelse(Home==sub,xGAway,xGHome),
    nsub=ifelse(Home==sub,Away,Home),
    HA=ifelse(Home==sub,"H","A"),
    ) %>%
  pivot_longer(
    cols=c(xGF,xGA),
    names_to="team",
    values_to="teamxG",
  ) %>%
  ggplot(aes(x=Wk,y=teamxG,colour=team)) +
  geom_point() +
  geom_line()

# df <- data.frame(
#   Home=c("Team1","Team3","Team5"),
#   Away=c("Team2","Team4","Team6"),
#   GoalsHome=c(3,0,1),
#   GoalsAway=c(0,2,1)
# )

# df %>%
#   pivot_longer(
#     cols=c(Home,Away),
#     names_to="HomeAway",
#     values_to="Team"
#   ) %>%
#   left_join(
#     df
#   )

# df_long <- data.frame(
#   Team=c("Team1","Team2","Team3","Team4","Team5","Team6"),
#   Opposition=c("Team2","Team1","Team4","Team3","Team6","Team5"),
#   GoalsF=c(3,0,0,2,1,1),
#   GoalsA=c(0,3,2,0,1,1)
# )

# minutes played by position


# goals by nationality
players %>%
  filter(Squad=="Southampton") %>%
  # mutate(Gls=ifelse(Player %in% c("Jan Bednarek","Shane Long"),Gls+1,Gls)) %>%
  group_by(Nation) %>%
  tally(Gls) %>%
  rename("Gls"="n") %>%
  mutate(Nation=fct_reorder(Nation,Gls)) %>%
  filter(Gls!=0) %>%
  ggplot(aes(x=Nation,y=Gls,fill=Nation)) +
  geom_bar(stat="identity") +
  theme_sfc() +
  labs(title="Southampton goals by country",
       x=element_blank(),
       y=element_blank()) +
  scale_fill_manual(values=col_medium) +
  coord_flip()

# players_new <- players %>%
#   filter(Squad=="Southampton") %>%
#   mutate(Gls=ifelse(Player %in% c("Jan Bednarek","Shane Long"),Gls+1,Gls))

# players_new["Player"=="Jan Bednarek","Gls"]
# players_new[10,"Gls"`:=`100]
# players_new[,Gls = 100]
# players_new[, a:=1]

# class(players_new)
# 
# players_new %>% view

players %>%
  filter(Squad=="Southampton") %>%
  filter(!is.na(`Gls+/-`)) %>%
  mutate(Player=fct_reorder(Player,`Gls+/-`)) %>%
  mutate(PlusMinusPos=ifelse(`Gls+/-`>=0,TRUE,FALSE)) %>%
  ggplot(aes(x=Player,y=`Gls+/-`)) +
  geom_bar(aes(fill=PlusMinusPos),stat="identity",width=0.8,alpha=0.6) +
  theme_sfc() +
  theme(axis.text.x=element_text(hjust=0.5)) +
  labs(title="On-pitch goal difference",
       x=element_blank(),
       y="Goals scored - Goals conceded",
       caption=caption[[1]]) +
  scale_fill_manual(values=c(col_gdocs[[2]],col_gdocs[[4]])) +
  scale_y_reverse(breaks=seq(-100,100,2),expand=expand_scale(add=0.2)) +
  coord_flip()

players %>%
  filter(Squad=="Southampton") %>%
  filter(!is.na(Min)) %>%
  mutate(
    Min=replace(Min,is.na(Min),0),
    Subs=replace(Subs,is.na(Subs),0),
    `Mn/Sub`=replace(`Mn/Sub`,is.na(`Mn/Sub`),0),
    MinSub=Subs*`Mn/Sub`,
    MinStart=Min-MinSub,
    ) %>%
  mutate(
    Pos1=ifelse(Player %in% c("Kevin Danso","Jannik Vestergaard","Jan Bednarek","Jack Stephens","Maya Yoshida"),"CB",Pos1),
    Pos1=ifelse(Player %in% c("Ryan Bertrand","Cédric Soares","Yan Valery"),"FB",Pos1),
    Pos1=ifelse(Player %in% c("James Ward-Prowse","Pierre Højbjerg","Oriol Romeu","William Smallbone"),"DM",Pos1),
    Pos1=ifelse(Player %in% c("Nathan Redmond","Stuart Armstrong","Sofiane Boufal","Moussa Djenepo"),"AM",Pos1),
  ) %>%
  mutate(Possfc=factor(Pos1,levels=c("GK","CB","FB","DM","AM","FW"))) %>%
  mutate(Player=fct_reorder(Player,Min)) %>%
  ggplot(aes(x=Min,y=Player)) +
  geom_segment(aes(y=Player,yend=Player,x=0,xend=MinStart),colour=sfc,size=3.5,alpha=0.8) +
  geom_segment(aes(y=Player,yend=Player,x=MinStart,xend=Min),colour=sfc,size=3.5,alpha=0.3) +
  theme_sfc() +
  labs(title="League minutes",
       subtitle="(from start / from bench)",
       x=element_blank(),
       y=element_blank(),
       caption=caption[[1]]) +
  expand_limits(Min=0) +
  scale_x_continuous(breaks=seq(0,90*38,180),expand=expand_scale(add=c(20,20))) +
  theme(
    axis.line=element_blank(),
    axis.text.x=element_text(size=rel(0.8),hjust=0.5),
    axis.text.y=element_text(size=rel(0.8)),
    strip.background=element_blank(),
    strip.text.y=element_text(colour="black",face="bold",angle=0),
  ) +
  facet_grid(Possfc ~ .,scales="free",space="free")

players %>%
  filter(Squad=="Southampton") %>%
  filter(!is.na(`Gls+/-`)) %>%
  mutate(Player=fct_reorder(Player,`Gls+/-`)) %>%
  mutate(Pos=ifelse(`Gls+/-`>=0,TRUE,FALSE)) %>%
  ggplot(aes(x=`Gls+/-`,y=Player,colour=Pos)) +
  geom_segment(aes(x=0,xend=`Gls+/-`,y=Player,yend=Player),size=4,alpha=0.8) +
  theme_sfc() +
  labs(title="On-pitch goal difference",
       x=element_blank(),
       y="Goals scored - Goals conceded",
       caption=caption[[1]]) +
  scale_colour_manual(values=c(col_medium[8],col_medium[3])) +
  scale_x_reverse(breaks=seq(-100,100,2),expand=expand_scale(add=0.1))

# match xG plots
matches_long %>%
  filter(Team=="Southampton") %>%
  filter(!is.na(GF)) %>%
  ggplot(aes(x=xGF,y=Wk)) +
  geom_segment(aes(x=0,xend=xGF,y=Wk,yend=Wk),size=3,alpha=0.8,colour=col_medium[8]) +
  geom_segment(aes(x=0,xend=-xGA,y=Wk,yend=Wk),size=3,alpha=0.8,colour=col_medium[3]) +
  theme_epl() +
  scale_x_reverse(breaks=seq(-10,10,0.5),expand=expand_scale(add=0.1))

squad %>%
  ggplot(aes(x=npxG,y=Sh,colour=Squad)) +
  geom_point() +
  geom_text_repel(aes(label=Squad),size=3) +
  theme_epl() +
  scale_colour_manual(values=palette_epl())

squad %>%
  ggplot(aes(x=PPA,y=`1/3`,colour=Squad)) +
  geom_point() +
  geom_text_repel(aes(label=Squad),size=3) +
  theme_epl() +
  scale_colour_manual(values=palette_epl())
```
