---
#title: "tracking"
#author: "szfh"
#date: "2020-04-12"
output: github_document
---

```{r setup, include=F}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE)
pacman::p_load(
  pacman,
  here,
  tidyverse,
  magrittr,
  readr,
  knitr,
  CodaBonito,
  ggsoccer,
  magick
)

# devtools::install_github("thecomeonman/CodaBonito")
# https://github.com/thecomeonman/CodaBonito
# https://github.com/thecomeonman/MakingFriendsWithTrackingData

cDataRootFolder = here("data","tracking")
cGameName = "Sample_Game_1"
nXLimit = 120
nYLimit = 80
dtData <- readRDS(here("data","tracking","Sample_Game_1","game1.rds"))
```

```{r parsedata, include=F, eval=F}
# run to parse data and save locally
dtData <- fParseTrackingDataBothTeams(
  cRootPath = cDataRootFolder,
  cGameName = cGameName,
  nXLimit = nXLimit,
  nYLimit = nYLimit,
  xMaxBB = 1,
  yMaxBB = 1
)

saveRDS(game1, here("data","tracking","Sample_Game_1","game1.rds"))
```

## View data

```{r view, include=F, echo=F}
dtData$dtTrackingData %>%
  str(give.attr=FALSE)
dtData$dtEventsData %>%
  str(give.attr=FALSE)
dtData$dtEventsData %>%
  select("Type") %>%
  distinct()
dtData$dtEventsData %>%
  select("Subtype") %>%
  distinct()
dtData$dtEventsData %>%
  select("Type","Subtype") %>%
distinct()
```

## Events

```{r events}
goal_kicks <- dtData$dtEventsData %>%
  filter(Subtype=="GOAL KICK")

corner_kicks <- dtData$dtEventsData %>%
  filter(Subtype=="CORNER KICK")
```

## Slice

```{r slice}
fGetTrackingSlice <- function(dtTrackingData, frame, before=0, after=0){
  
  dtTrackingSlice <- dtTrackingData %>%
    filter(Frame %in% outer(frame,-before:after,"+"))

  return(dtTrackingSlice)
}

dtTrackingSlice <- fGetTrackingSlice(
  dtData$dtTrackingData,
  frame=goal_kicks$StartFrame[c(10)],
  before=20, # frames before event
  after=200 # frames after event
)

# framesinslice <- dtTrackingSlice %>%
#   select(Frame) %>%
#   distinct()
```

## Voronoi

```{r voronoi}
voronoiOutput <- fDrawVoronoiFromTable(
   dtTrackingSlice = dtTrackingSlice,
   nXLimit = 120,
   nYLimit = 80,
   UseOneFrameEvery = 6,
   DelayBetweenFrames = 12,
   markTrajectoryFor = c('AwayPlayer18')
)

file.remove(here("plots","tracking","voronoigk10.gif"))
file.copy(voronoiOutput, here("plots","tracking","voronoigk10.gif"))

# if ( !interactive() ) {
#     
#     qwe = suppressWarnings(
#         file.remove('./README_files/figure-markdown_strict/Voronoi.gif')
#     )
#     rm(qwe)
# 
#     qwe = file.copy(
#         voronoiOutput,
#         './README_files/figure-markdown_strict/Voronoi.gif'
#     )
# 
#     rm(qwe)
#     
# }
```

## Maps

```{r maps}
goal_kicks <- dtData$dtEventsData %>%
  filter(Subtype=="GOAL KICK")

corner_kicks <- dtData$dtEventsData %>%
  filter(Subtype=="CORNER KICK")

# pPitch <- fAddPitchLines(ggplot()) + theme_pitch()
# 
# pPitch +
#   geom_segment(data=goal_kicks,aes(x=EventStartX,y=EventStartY,xend=EventEndX,yend=EventEndY,colour=Team),size=1, arrow=arrow(length = unit(0.03, "npc"))) +
#   theme(
#     plot.title=element_text(size=16, hjust=0.5, face="bold"),
#     plot.caption=element_text(size=10, face="bold"),
#     legend.position="none"
#   ) +
#   labs(
#     title="Sample match 1 - Goal kicks",
#     caption="Tracking data: @MetricaSports"
#   )
# ggsave((here("plots","tracking","goalkicks.jpg")))
```
